In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import gradio as gr
import requests
import io

In [2]:
url = "https://raw.githubusercontent.com/ANIKETwakodikar/chennai-housing-dataset/main/Chennai.csv" 
download = requests.get(url).content
df = pd.read_csv(io.StringIO(download.decode('utf-8')))

af=df.drop(columns=['Price', 'Location', 'Resale',"24X7Security",
       'MaintenanceStaff', 'Gymnasium', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', "Children'splayarea", 'VaastuCompliant', 'Microwave', 'GolfCourse',
       'DiningTable', 'Wardrobe'])

In [3]:
model=linear_model.LinearRegression()
model.fit(af,df['Price'])
af

,Area,No. of Bedrooms,SwimmingPool,WashingMachine,Gasconnection,AC,Wifi,LiftAvailable,BED,TV,Sofa,Refrigerator
0,1310,3,0,0,0,0,0,0,0,0,0,0
1,1126,2,1,0,0,0,0,1,0,0,0,0
2,1307,3,1,0,0,0,0,0,0,0,0,0
3,3600,3,1,0,0,0,0,0,0,0,0,0
4,1700,3,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5009,1599,3,9,9,9,9,9,9,9,9,9,9
5010,740,2,9,9,9,9,9,9,9,9,9,9
5011,1700,3,9,9,9,9,9,9,9,9,9,9
5012,1599,3,9,9,9,9,9,9,9,9,9,9
5013,688,2,9,9,9,9,9,9,9,9,9,9

In [4]:
def tello(area,no_of_bedrooms,swimming_pool,Washing_Machine,Gas_connection,AC,wifi,lift,beds,TV,sofa,fridge):
    a=int(model.predict([[area,no_of_bedrooms,swimming_pool,Washing_Machine,Gas_connection,AC,wifi,lift,beds,TV,sofa,fridge]]))
    if a>10000000:
        return str(a//10000000)+' Cr'
    else:
        return str(a//100000)+' L'

In [5]:
model_gr=gr.Interface(tello,inputs=["number","number","number","number","number","number","number","number","number","number","number","number"],outputs='text')
model_gr.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

In [6]:
# https://raw.githubusercontent.com/ANIKETwakodikar/chennai-housing-dataset/main/Chennai.csv

/home/aniket/.local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/aniket/.local/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(